export const GET_RANDOM_PERSON = 'GET_RANDOM_PERSON';
export const GET_LIST_RANDOM_PERSON = 'GET_LIST_RANDOM_PERSON';
export const UPDATE_LIST_RANDOM_PERSON = 'UPDATE_LIST_RANDOM_PERSON';
export const UPDATE_LIST_FAVORITE_PERSON = 'UPDATE_LIST_FAVORITE_PERSON';
export const DELETE_RANDOM_PERSON = 'DELETE_RANDOM_PERSON';

export const CLEAR_LIST_FAVORITE_PERSON = 'CLEAR_LIST_FAVORITE_PERSON';

export const IS_GETTING_RANDOM_PERSON = 'IS_GETTING_RANDOM_PERSON';
export const IS_GETTING_LIST_RANDOM_PERSON = 'IS_GETTING_LIST_RANDOM_PERSON';
